# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
target 'qqhrLive' do

pod 'Alamofire'
pod 'Kingfisher'


end
